apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disco-db
  template:
    metadata:
      labels:
        app: disco-db
    spec:
      containers:
      - name: disco-mongo
        image: pxrsival/mongo-disco-img:v1
        ports:
        - containerPort: 27017