# [ETAPA DE COMPILACIÓN]
# USEMOS UNA IMAGEN DE MAVEN COMPATIBLE CON JAVA JDK 17, LE ASIGNAREMOS "build" A MODO DE ALIAS
FROM maven:3.8.4-openjdk-17 AS build

# ESTABLECEMOS VARIABLES DE ENTORNO POR DEFECTO (EL PROYECTO SE COMPILARÁ CON ESTOS VALORES)
ENV MONGO_HOSTNAME=mongo-service
ENV MONGO_PORT=27017
ENV MONGO_AUTHDB=admin
ENV MONGO_DB=discodb
ENV MONGO_USR=disco_owner
ENV MONGO_PWD=disco_password
ENV TOMCAT_PORT=8083
ENV API_PATH=/api

# ESTABLECEMOS UNA CARPETA DE TRABAJO QUE CONTENDRÁ EL CÓDIGO DE NUESTRA APLICACIÓN. TODAS LAS DEMÁS INSTRUCCIONES Y COMANDOS SE EJECUTARÁN EN ESTE DIRECTORIO DE TRABAJO
WORKDIR /app

# DESPUÉS DE CREAR EL DIRECTORIO /app, COPIAMOS EL CÓDIGO DE JAVA
COPY diplo-cloud-disco-service /app

# CON LA SIGUIENTE INSTRUCCIÓN COMPILAMOS LA APLICACIÓN
RUN mvn clean install

# [ETAPA DE EJECUCIÓN]

# EXPONEMOS EL PUERTO 8083 QUE ES EL NECESARIO PARA QUE FUNCIONE NUESTRA APLICACIÓN
EXPOSE 8083

# CON EL SIGUIENTE COMANDO SE EJECUTA LA APLICACIÓN SPRINGBOOT (EN CONSOLA ES COMO SI SE ESCRIBIERA "java -jar /app/target/...").
CMD ["java", "-jar", "target/disco-service-0.0.1-SNAPSHOT.jar"]