# TRABAJAREMOS CON LA IMAGEN DE MONGO 4.2.24
FROM mongo:4.2.24

# INICILIZAMOS MONGO CON LA CONFIGURACIÓN REQUERIDA (USUARIO, CONTRASEÑA Y BD). OPCIONALMENTE SE PUEDE INICIALIZAR CON DATOS DE PRUEBA
# PARA ELLO COPIAMOS EL SCRIPT DE INICIALIZACIÓN AL DIRECTORIO /docker-entrypoint-initdb.d/ EN LA IMAGEN. ESTE ES UN DIRECTORIO EN LA IMAGEN DE MONGO QUE SE UTILIZA PARA CARGAR ARCHIVOS DE INICIALIZACIÓN CUANDO EL CONTENEDOR SE EJECUTA POR PRIMERA VEZ
COPY init-mongo.js /docker-entrypoint-initdb.d/


# EXPONEMOS EL PUERTO 27017 PARA QUE PUEDA SER ALCANZADO POR OTRO CONTENEDOR
EXPOSE 27017