apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: disco-db
  template:
    metadata:
      labels:
        app: disco-db
    spec:
      containers:
      - name: disco-mongo
        image: pxrsival/mongo-disco-img:v1
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: disco-db # SELECCIONAMOS LOS PODS CON ESTA ETIQUETA
  ports:
    - protocol: TCP
      port: 27017 # PUERTO POR EL QUE EL SERVICIO VA A ESTAR ESCUCHANDO
      targetPort: 27017 # PUERTO AL QUE SE VA A DIRIGIR EL TRÁFICO QUE ENTRA POR "PORT"